####################################################
# Checks about the pre-commit configuration itself #
####################################################

repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply      # Ensures all defined hooks affect at least one file in the repo
    -   id: check-useless-excludes # Ensures all defined excludes apply to at least one file in the repo

###########################
# General use / built-ins #
###########################

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace  # Removes trailing whitespace from lines in all file types
    -   id: end-of-file-fixer    # Fixes last line of all file types
    -   id: check-merge-conflict # Checks if you're about to commit a file that hasn't had conflicts resolved
    -   id: no-commit-to-branch  # Checks if you're committing to a disallowed branch
        args: [--branch, dev]
    -   id: check-ast            # Checks that Python files are valid syntax
    -   id: check-toml           # Checks TOML files for syntax errors

##########
# Python #
##########

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
    -   id: ruff-check
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    -   id: mypy
        additional_dependencies: [typing_extensions, types-requests, types-urllib3]
